export default defineEventHandler((event) => {
  return [
    {
      "name": "Politeknik Negeri Madiun",
      "logo": "/images/education/pnm.png",
      "web": "https://www.pnm.ac.id",
      "level": "university",
      "grade": "Diploma 3 (D3)",
      "departement": "Teknik",
      "study_program": "Teknologi Informasi",
      "start": "2022-07-12",
      "end": null,
      "place": "Jl. Serayu, Taman, Kota Madiun, Jawa Timur"
    },
    {
      "name": "SMA Negeri 1 Ngawi",
      "logo": "/images/education/smasa.jpeg",
      "web": "https://www.sman1ngawi.sch.id",
      "level": "shs",
      "grade": null,
      "departement": "Matematika dan IPA",
      "study_program": null,
      "start": "2018-07-12",
      "end": "2021-03-17",
      "place": "Jl. Ahmad Yani No.45, Wareng, Beran, Kec. Ngawi, Kabupaten Ngawi, Jawa Timur 63216",
    },
    {
      "name": "SMP Negeri 1 Padas",
      "logo": null,
      "web": null,
      "level": "jhs",
      "grade": null,
      "departement": null,
      "study_program": null,
      "start": "2015-07-12",
      "end": "2018-03-17",
      "place": "Jl. Raya Padas-Ngawi, Padas I, Padas, Kec. Padas, Kabupaten Ngawi, Jawa Timur 63281",
    },
    {
      "name": "SD Negeri Munggut 1",
      "logo": null,
      "web": null,
      "level": "es",
      "grade": null,
      "departement": null,
      "study_program": null,
      "start": "2009-07-12",
      "end": "2015-06-17",
      "place": "Jl. A. Yani No.35, Munggut, Kec. Padas, Kabupaten Ngawi, Jawa Timur 63281",
    },
    {
      "name": "TPQ Al-Falahiyyah",
      "logo": null,
      "web": null,
      "level": "kg",
      "grade": null,
      "departement": null,
      "study_program": null,
      "start": "2007-05-21",
      "end": "2009-03-17",
      "place": "Tangerang, Banten",
    },
  ]
})