const data = [
    {
        id: 'sipdata-pemuda-mta-boyolali',
        status: 'proceed',
        category: 'web',
        name: 'SIPDATA Pemuda MTA Boyolali',
        techStack: ['laravel', 'bootstrap', 'javascript', 'php'],
        shortDesc: 'Sistem Informasi database Pemuda MTA Cabang Boyolali untuk memonitor segala aktifitas kajian hingga manajemen dari Perwakilan hingga ke Cabang.',
        image: '/images/portofolio/sipdata-front.png',
    },
    {
        id: 'cakadi-web',
        status: 'success',
        category: 'web',
        name: 'Personal Website Cak Adi',
        techStack: ['nuxtjs', 'tailwindcss', 'typescript', 'javascript', 'nodejs'],
        shortDesc: 'Ini adalah website personal milik Cak Adi (Saya Sendiri) untuk menampilkan semua informasi tentang diri saya pribadi.',
        image: '/images/portofolio/cakadi-home.png',
    },
    {
        id: 'cakadi-web',
        status: 'success',
        category: 'web',
        name: 'Siperpus PHP Native',
        techStack: ['bootstrap', 'php', 'javascript', 'html5', 'css3'],
        shortDesc: 'Website ujian akhir semester 2 dengan membangun proyek website SIPERPUS yang dibangun dengan PHP Native.',
        image: '/images/portofolio/siperpus-front.png',
    },
    {
        id: 'cakadi-web',
        status: 'success',
        category: 'web',
        name: 'Sistem Sewa Laptop',
        techStack: ['bootstrap', 'php', 'javascript', 'html5', 'css3'],
        shortDesc: 'Website ujian akhir semester 2 untuk teman saya dengan membangun proyek website Sistem Sewa Laptop yang dibangun dengan PHP Native.',
        image: '/images/portofolio/sewa-laptop-front.png',
    },
    {
        id: 'perkopian-duniawi',
        status: 'success',
        category: 'mobile',
        name: 'Perkopian Duniawi',
        techStack: ['kotlin', 'java', 'android'],
        shortDesc: 'Proyek UAS pemrograman mobile dengan membangun aplikasi android yang menampilkan daftar tempat cafe buat nongki.',
        image: '/images/portofolio/perkopian-duniawi-show.png',
    },
    {
        id: 'sidasi',
        status: 'success',
        category: 'web',
        name: 'Sistem Data Organisasi',
        techStack: ['laravel', 'bootstrap', 'javascript', 'jquery', 'php'],
        shortDesc: 'Website untuk mengelola, memantau dan mengevaluasi kinerja sebuah organisasi.',
        image: '/images/portofolio/sidasi-front.png',
    },
    {
        id: 'supedes',
        status: 'success',
        category: 'web',
        name: 'Surat Pengantar Desa',
        techStack: ['laravel', 'bootstrap', 'javascript', 'jquery', 'php'],
        shortDesc: 'Website untuk mengelola kepengurusan surat pengantar desa secara daring.',
        image: '/images/portofolio/supedes-submission.png',
    },
    {
        id: 'sirus-intechfes',
        status: 'success',
        category: 'web',
        name: 'Landing Sirus (Sistem Informasi Rumah Sakit)',
        techStack: ['nuxtjs', 'bootstrap', 'javascript', 'nodejs'],
        shortDesc: 'Website landing page untuk perlombaan IntechFest 2021 Politeknik Negeri Bali dan mendapatkan peringkat 1 dalam perlombaan tersebut.',
        image: '/images/portofolio/sirus-front.png',
    },
    {
        id: 'sideka-dkd',
        status: 'pending',
        category: 'web',
        name: 'Sistem Informasi Dewan Kerja',
        techStack: ['laravel', 'bootstrap', 'javascript', 'jquery', 'php'],
        shortDesc: 'Sistem Informasi untuk mengelola dan memonitor seluruh aktifitas kegiatan di Dewan Kerja seluruh Jawa Timur.',
        image: '/images/portofolio/sideka-front.png',
    },
    {
        id: 'deptics-project',
        status: 'success',
        category: 'web',
        name: 'Deptics 2021 Project',
        techStack: ['html5', 'bootstrap', 'javascript', 'jquery', 'css3'],
        shortDesc: 'Website perlombaan desain web dengan tema pandemi COVID-19 pada perlombaan Deptics UNIPMA Madiun dan mendapatkan peringkat 1 dalam lomba tersebut.',
        image: '/images/portofolio/kawal-covid-main.png',
    },
    {
        id: 'append-disperindag',
        status: 'success',
        category: 'web',
        name: 'Append Disperindag',
        techStack: ['laravel', 'bootstrap', 'javascript', 'jquery', 'php'],
        shortDesc: 'Website untuk manajemen data pemerataan bantuan dari pemerintah untuk para pelaku UMKM di Provinsi Papua.',
        image: '/images/portofolio/append-front.png',
    },
    {
        id: 'pilketos-smp',
        status: 'success',
        category: 'web',
        name: 'Sistem Pemilihan Ketua OSIS',
        techStack: ['laravel', 'bootstrap', 'javascript', 'jquery', 'php'],
        shortDesc: 'Website untuk manajemen menjalankan kegiatan pemilihan OSIS pada suatu sekolah menengah pertama secara daring.',
        image: '/images/portofolio/pilketos-front.png',
    },
    {
        id: 'bytesfest-project',
        status: 'success',
        category: 'web',
        name: 'BytesFest 2021 Project',
        techStack: ['html5', 'bootstrap', 'javascript', 'jquery', 'css3'],
        shortDesc: 'Website perlombaan desain web dalam bentuk toko online pada perlombaan BytesFest UNS 2021 dan mendapatkan peringkat 1 dalam lomba tersebut.',
        image: '/images/portofolio/bytesfest-front.png',
    },
    {
        id: 'ppdb-mahasiswa',
        status: 'success',
        category: 'web',
        name: 'PMB Eltibiz',
        techStack: ['laravel', 'bootstrap', 'javascript', 'jquery', 'php'],
        shortDesc: 'Sistem Website untuk mengelola Penerimaan Mahasiswa Baru, dan ini adalah proyek kolaborasi dengan tugas akhir seorang mahasiswa.',
        image: '/images/portofolio/ppdb-login.png',
    },
    {
        id: 'ticket-hypenamic',
        status: 'cancel',
        category: 'web',
        name: 'SiTiket',
        techStack: ['laravel', 'bootstrap', 'javascript', 'jquery', 'php'],
        shortDesc: 'Sistem Website untuk menjual dan mengelola data penjualan tiket sebuah event seperti konser musik, acara amal dan lainnya.',
        image: '/images/portofolio/ticket-front.png',
    },
]

export default defineEventHandler(async (event) => {
    const query = getQuery(event);
    let datas: any = [];

    if(query.slug) datas = data.filter((data) => data.id === query.slug)
    else datas = data

    return datas;
})